// Export all icons from a single file
export { default as AddIcon } from './AddIcon';
export { default as CancelIcon } from './CancelIcon';
export { default as DeleteIcon } from './DeleteIcon';
export { default as EditIcon } from './EditIcon';
export { default as MoonIcon } from './MoonIcon';
export { default as RestoreIcon } from './RestoreIcon';
export { default as SaveIcon } from './SaveIcon';
export { default as SunIcon } from './SunIcon';
export { default as TrashIcon } from './TrashIcon';